# Generated by Django 2.0.5 on 2018-05-13 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='ending_time',
            field=models.DateField(default=datetime.datetime(2018, 6, 12, 1, 11, 37, 768321), verbose_name='应还时间'),
        ),
    ]
