# Generated by Django 2.0.5 on 2018-05-13 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180513_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='ending_time',
            field=models.DateField(default=datetime.datetime(2018, 6, 12, 11, 12, 26, 577171), verbose_name='应还时间'),
        ),
    ]
