# Generated by Django 2.0.5 on 2018-05-12 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='卡号')),
                ('balance', models.FloatField(choices=[('valid', '有效'), ('invalid', '无效')], verbose_name='余额')),
                ('state', models.CharField(max_length=10, verbose_name='状态')),
                ('crate_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
            ],
            options={
                'verbose_name': '校园卡信息',
                'verbose_name_plural': '校园卡信息',
            },
        ),
    ]
