# Generated by Django 2.0.5 on 2018-05-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180513_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='aa', max_length=20, verbose_name='姓名'),
            preserve_default=False,
        ),
    ]
